export const types = {
  loginTeacherGoogle: '[Auth] LoginTeacherGoogle',
  loginTeacherEmail: '[Auth] LoginTeacherEmail',
  registerTeacherGoogle: '[Auth] RegisterTeacherGoogle',
  registerTeacherEmail: '[Auth] RegisterTeacherEmail',
  loginStudentGoogle: '[Auth] LoginStudentGoogle',
  loginStudentEmail: '[Auth] LoginStudentEmail',
  registerStudentGoogle: '[Auth] RegisterStudentGoogle',
  registerStudentEmail: '[Auth] RegisterStudentEmail',
  logout: '[Auth] Logout',
  userActive: '[AUTH] UserActive',
  removeUser: '[AUTH] RemoveUSer',
  userToRegister: '[AUTH] UserToRegister',

  uiRegisterTeacher: '[UI] RegisterTeacher',
  uiRegisterStudent: '[UI] RegisterStudent',
  uiLoginTeacher: '[UI] LoginTeacher',
  uiLoginStudent: '[UI] LoginStudent',
  uiStartLoading: '[UI] StartLoading',
  uiFinishLoading: '[UI] FinishLoading',
  uiRegisterGoogle: '[UI] RegisterWithGoogle',
  uiLoadingSplashScreen: '[UI] LoadingSplashScreen',
  uiShowModalRegister: '[UI] ShowModalRegister',

  getTeachers: '[T] GetTeachers',
  getKeyTeachers: '[T] GetKeyTeachers',
};
