export const types = {
  userActive: '[AUTH] UserActive',
  removeUser: '[AUTH] RemoveUSer',
  userToRegister: '[AUTH] UserToRegister',
  logout: '[Auth] Logout',

  uiLoading: '[UI] Loading',
  uiLoginTeacher: '[UI] LoginTeacher',
  uiLoadingSplashScreen: '[UI] LoadingSplashScreen',
  uiShowModalRegister: '[UI] ShowModalRegister',
  uiShowModalRegProd: '[UI] ShowModalRegProd',
  uiShowModalUpdProd: '[UI] ShowModalUpdProd',
  uiShowModalRegIngr: '[UI] ShowModalRegIngr',
  uiShowModalUpdIngr: '[UI] ShowModalUpdIngr',
  uiShowModalResult: '[UI] ShowModalResult',

  getTeachers: '[USER] GetTeachers',
  getStudents: '[USER] GetStudents',
  getStudentsVerified: '[USER] GetStudentsVerified',
  getKeyTeachers: '[USER] GetKeyTeachers',
  updateUserData: '[USER] UpdateUserData',

  getCategories: '[DATA] GetCategories',
  getClassifications: '[DATA] GetClassifications',
  getProducts: '[DATA] GetProducts',
  getIngredients: '[DATA] GetIngredients',
  getRequirements: '[DATA] GetRequirements',
  selectedIngredients: '[DATA] SelectedIngredients',
  selectedData: '[DATA] SelectedData',
};
